title: Yifan Gao (高一帆)
logo: /assets/img/1fan_msra.jpg
description: Ph.D. student, CSE, CUHK
research: Text Generation, Dialogue, Natural Language Processing
social:  <a href="https://github.com/Evan-Gao">Github</a>, <a href="https://scholar.google.com.hk/citations?user=erdMFJwAAAAJ&hl=en&oi=ao">Google Scholar</a>
email: Email &#58 yifangao95 AT gmail.com
show_downloads: false
google_analytics: UA-126219209-1
theme: jekyll-theme-minimal
